### ISSUE TITLE
InputError: no module named 'requests'

### ISSUE THREAD

**Issue by Zyrbleblurb** [harag-on-steam/se-blender#12]
I get this error while trying to load your plugin in blender 2.77. If I drop the plugin in the plugins folder, itll give the same error when trying to select it from the list.

Trying to upload an image of the long error message. It references 3 python files and then ends with InputError: no module named 'requests'

I tried looking for a solution online, and this error seems to need another library in python that it doesnt come with for "requests", but adding that library then just makes blender immediately crash when the plugin is selected.

![input error](https://cloud.githubusercontent.com/assets/18095529/14068189/757449b6-f449-11e5-9da3-e4190054688f.jpg)

The same thing happens in Blender 2.76. In 2.72, it just crashes.

**Comment by harag-on-steam** [comment]
That's odd. On my system `<blender-installdir>\2.77\python\lib\site-packages` has the module `requests` and is [supposed to have it](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/22a2853b5d5636d5b47407f1e854d47f9b57c295:/CMakeLists.txt#l2870).

Your filepaths tell me you are on Windows. How did you install Blender? Are using Blender with your system's Python installation (not the default)?

**Comment by Zyrbleblurb** [comment]
Ive installed blender through the zip, and msi. What happens with either is that blender will not open and gives an "exception_illegal_instruction" error and shuts down on start. I found copying the python folder from windows into blender allows blender to start, but if 'requests' is there, it will crash upon clicking the plugin.

Using python 3.51

**Comment by harag-on-steam** [comment]
Blender shouldn't crash with that exception. Are you using the correct variant for your system? There's a 32bit and a 64bit variant. You need to use the one that matches your operating system.

**Comment by Zyrbleblurb** [comment]
I have vista 64, Im using blender 64 as well. I had not seen that bug report, but did see another one discussing the same issue. I had tried what that bug report suggested of uninstalling python and trying to run blender alone, but nothing changed. My OS is up to date with updates.

Its something python related I guess, because if I replace the default blender python folder with the 3.51 python, it will run, but will give the error I mentioned above when selecting the plugin. And the folder is actually missing the requests module. If I add in the requests module, it crashes, but if cmd prompt is open, it will actually note the crash error, which is right back to "exception illegal instruction".

Since this seems to be a blender/python/somethinginmyOS problem, Ill post this on the blender forums and try to get someone there to help me as to not waste your time, unless you have any other suggestions for me.

Thank you for your time and responding to this problem.

**Comment by harag-on-steam** [comment]
I'm closing this then. Feel free to re-open if necessary.
