### ISSUE TITLE
LOD not showing up in game

### ISSUE THREAD

**Issue by jkalousek** [harag-on-steam/se-blender#13]
I started adding Levels of details to my models. At first everything seams ok, xml includes information about LOD, mwm file with _LOD is generated but for some reason game is not using them. I tried everything that came to my mind, and can't figure out why is this happening. Did you have any problem with it? Or is there some step that I'm possibly missing?
Btw. thank you for this awesome add-on to Blender!

**Comment by harag-on-steam** [comment]
I guess [this reported bug in the engine](http://forums.keenswh.com/threads/1-105-directx-11-renderer-is-unable-to-load-level-of-detail-models.7371600/#post-1286886624) is still present. You can verify if your LODs are setup correctly by copying them into the game's folder (details in the bug report).

**Comment by harag-on-steam** [comment]
I just verfied myself. The bug in the engine is still present.

**Comment by jkalousek** [comment]
Thank you for information, let's hope they fix is soon.
