### ISSUE TITLE
Cannot read color and alpha from the same image-texture node

### ISSUE THREAD

**Issue by harag-on-steam** [harag-on-steam/se-blender#6]
Currently the shader node-group that renders DirectX 11 textures produces some undesired rendering artifacts when both the color and alpha output of the same image-texture node are connected to it. 

![rendering artifacts](https://cloud.githubusercontent.com/assets/8539331/8150266/54f139f8-12e3-11e5-8eea-29988f0b63ac.jpg)

It seems Blender does not expect that several, unrelated image channels are contained in one image file and [premultiplies the color output](https://www.blender.org/manual/render/cycles/nodes/textures.html#image-texture) if the alpha output is used. That might be the cause for the rendering artifacts.

[1] [forum-link](http://forums.keenswh.com/threads/7285972/page-7#post-1286782564) with further details about the shader setup.

**Comment by WorldSEnder** [comment]
I'm assigning myself to this :) See also http://blender.stackexchange.com/questions/32450/how-to-separate-texture-alpha-without-premultiplying-the-color

**Comment by WorldSEnder** [comment]
Unfortunatly, #blendercoders says it is impossible to turn off premultiplication in one Image Node.

chat log: http://pastebin.com/6DV5YX5b

**Comment by harag-on-steam** [comment]
Well, not entirely unexpected. Anyway, thanks for looking into it. Now I'll have to think about how to do work around this. Maybe I can synchronize two image nodes via setter-methods in the UI.

**Comment by harag-on-steam** [comment]
Resolved in 5eb9a18526cd41aa8e12123ad523717c8e1e25dc by using two images nodes and synchronizing them via a [scene update handler](https://github.com/harag-on-steam/se-blender/commit/5eb9a18526cd41aa8e12123ad523717c8e1e25dc#diff-402c24e65eb2e624bc2b284dd7792c4eR761).
