### ISSUE TITLE
Space Engineers menu is not opening up

### ISSUE THREAD

**Issue by mjc4wilton** [harag-on-steam/se-blender#7]
in the left-hand port under "Create" there is no Space engineers menu... I have tried re-launching blender, moving all the havok tools to the havok menu, and I know I hit the save button

**Comment by harag-on-steam** [comment]
On the Scene properties tab: Is the scene actually marked as a Space Engineer's block?

![enable_scene](https://cloud.githubusercontent.com/assets/8539331/8321453/5b5465d6-1a27-11e5-9dc8-75d5f67ed084.png)

**Comment by mjc4wilton** [comment]
You should probably add that ino the documentation because it was almost a turning point for me

**Comment by harag-on-steam** [comment]
You are probably right :blush:
